/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.com.cafi.barzinhodesktop.visao;

import bo.ProdutoBO;
import bo.UsuarioBO;
import br.com.cafi.barzinhodesktop.modelo.entidade.Produto;
import br.com.cafi.barzinhodesktop.modelo.entidade.Usuario;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Jk-Sa
 */
public class CadastrarProduto extends javax.swing.JPanel {

    /**
     * @param precoCompraFormattedTextField the precoCompraFormattedTextField to set
     */
    public void setPrecoCompraFormattedTextField(javax.swing.JFormattedTextField precoCompraFormattedTextField) {
        this.precoCompraFormattedTextField = precoCompraFormattedTextField;
    }

    /**
     * @param precoVendaFormattedTextField the precoVendaFormattedTextField to set
     */
    public void setPrecoVendaFormattedTextField(javax.swing.JFormattedTextField precoVendaFormattedTextField) {
        this.precoVendaFormattedTextField = precoVendaFormattedTextField;
    }

    /**
     * @return the qtEstoqueFormattedTextField
     */
    public javax.swing.JFormattedTextField getQtEstoqueFormattedTextField() {
        return qtEstoqueFormattedTextField;
    }

    /**
     * @param qtEstoqueFormattedTextField the qtEstoqueFormattedTextField to set
     */
    public void setQtEstoqueFormattedTextField(javax.swing.JFormattedTextField qtEstoqueFormattedTextField) {
        this.qtEstoqueFormattedTextField = qtEstoqueFormattedTextField;
    }

    /**
     * @return the cancelarButton
     */
    public javax.swing.JButton getCancelarButton() {
        return cancelarButton;
    }

    /**
     * @return the jFormattedTextField1
     */
    public javax.swing.JFormattedTextField getPrecoCompraFormattedTextField() {
        return precoCompraFormattedTextField;
    }

    /**
     * @return the jFormattedTextField2
     */
    public javax.swing.JFormattedTextField getPrecoVendaFormattedTextField() {
        return precoVendaFormattedTextField;
    }

    /**
     * @return the jLabel1
     */
    public javax.swing.JLabel getjLabel1() {
        return jLabel1;
    }

    /**
     * @return the jLabel2
     */
    public javax.swing.JLabel getjLabel2() {
        return jLabel2;
    }

    /**
     * @return the jLabel3
     */
    public javax.swing.JLabel getjLabel3() {
        return jLabel3;
    }

    /**
     * @return the jTextField1
     */
    public javax.swing.JTextField getDescricaoTextField() {
        return descricaoTextFiel;
    }

    /**
     * @return the salvarButton
     */
    public javax.swing.JButton getSalvarButton() {
        return salvarButton;
    }


    /**
     * Creates new form CadastrarProduto
     */
    public CadastrarProduto(JInternalFrame jif) {
        initComponents();
        this.jif = jif;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        descricaoTextFiel = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        precoCompraFormattedTextField = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        precoVendaFormattedTextField = new javax.swing.JFormattedTextField();
        salvarButton = new javax.swing.JButton();
        cancelarButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        qtEstoqueFormattedTextField = new javax.swing.JFormattedTextField();

        jLabel1.setText("Descrição");

        descricaoTextFiel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descricaoTextFielActionPerformed(evt);
            }
        });

        jLabel2.setText("Preço Compra");

        precoCompraFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));

        jLabel3.setText("Preço Venda");

        precoVendaFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        precoVendaFormattedTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precoVendaFormattedTextFieldActionPerformed(evt);
            }
        });

        salvarButton.setText("Salvar");
        salvarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarButtonActionPerformed(evt);
            }
        });

        cancelarButton.setText("Cancelar");
        cancelarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarButtonActionPerformed(evt);
            }
        });

        jLabel4.setText("Qt. Estoque");

        qtEstoqueFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(precoCompraFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(descricaoTextFiel, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(qtEstoqueFormattedTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(precoVendaFormattedTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(salvarButton)
                        .addGap(59, 59, 59)
                        .addComponent(cancelarButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(descricaoTextFiel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(precoCompraFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(precoVendaFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(qtEstoqueFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salvarButton)
                    .addComponent(cancelarButton))
                .addContainerGap(58, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void descricaoTextFielActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descricaoTextFielActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descricaoTextFielActionPerformed

    private void precoVendaFormattedTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precoVendaFormattedTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_precoVendaFormattedTextFieldActionPerformed

    private void cancelarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarButtonActionPerformed
        jif.dispose();
    }//GEN-LAST:event_cancelarButtonActionPerformed

    private void salvarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarButtonActionPerformed
           if( !descricaoTextFiel.getText().equals("")
                && Double.parseDouble(precoCompraFormattedTextField.getText())> 0 
                   && Double.parseDouble(precoVendaFormattedTextField.getText())> 0 
                   && Double.parseDouble(qtEstoqueFormattedTextField.getText())> 0){
            
                Produto p = new Produto();
                p.setDescricao(descricaoTextFiel.getText());
                p.setPrecoCompra(Double.parseDouble(precoCompraFormattedTextField.getText()));
                p.setPrecoVenda(Double.parseDouble(precoVendaFormattedTextField.getText()));
                p.setQuantidadeEstoque(Double.parseDouble(qtEstoqueFormattedTextField.getText()));
                
                ProdutoBO bo = new ProdutoBO();
                bo.save(p);
                 JOptionPane.showMessageDialog(null,"Produto Salvo com sucesso");
            }
         
    }//GEN-LAST:event_salvarButtonActionPerformed

    private final JInternalFrame jif;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelarButton;
    private javax.swing.JTextField descricaoTextFiel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JFormattedTextField precoCompraFormattedTextField;
    private javax.swing.JFormattedTextField precoVendaFormattedTextField;
    private javax.swing.JFormattedTextField qtEstoqueFormattedTextField;
    private javax.swing.JButton salvarButton;
    // End of variables declaration//GEN-END:variables
}
