/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.com.cafi.barzinhodesktop.visao;

import bo.InsumoBO;
import bo.UsuarioBO;
import br.com.cafi.barzinhodesktop.modelo.entidade.Insumo;
import br.com.cafi.barzinhodesktop.modelo.entidade.Usuario;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Jk-Sa
 */
public class CadastrarInsumo extends javax.swing.JPanel {
    
    
    public CadastrarInsumo(JInternalFrame jif, Insumo i) {
        initComponents();
       this.jif = jif;
       this.insumo=i;
       descricaoTextFiel.setText(insumo.getDescricao());
       qtEstoqueFormattedTextField.setText(insumo.getQuantidadeEstoque()+"");
    }
    

    

    /**
     * @return the qtEstoqueFormattedTextField
     */
    public javax.swing.JFormattedTextField getQtEstoqueFormattedTextField() {
        return qtEstoqueFormattedTextField;
    }

    /**
     * @param qtEstoqueFormattedTextField the qtEstoqueFormattedTextField to set
     */
    public void setQtEstoqueFormattedTextField(javax.swing.JFormattedTextField qtEstoqueFormattedTextField) {
        this.qtEstoqueFormattedTextField = qtEstoqueFormattedTextField;
    }

    /**
     * @return the cancelarButton
     */
    public javax.swing.JButton getCancelarButton() {
        return cancelarButton;
    }

    /**
     * @return the jFormattedTextField1
     */
    

    /**
     * @return the jLabel1
     */
    public javax.swing.JLabel getjLabel1() {
        return jLabel1;
    }

    /**
     * @return the jLabel2
     */
   

    /**
     * @return the jTextField1
     */
    public javax.swing.JTextField getDescricaoTextField() {
        return descricaoTextFiel;
    }

    /**
     * @return the salvarButton
     */
    public javax.swing.JButton getSalvarButton() {
        return salvarButton;
    }


    /**
     * Creates new form CadastrarInsumo
     */
    public CadastrarInsumo(JInternalFrame jif) {
        initComponents();
        this.jif = jif;
        this.insumo = new Insumo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        descricaoTextFiel = new javax.swing.JTextField();
        salvarButton = new javax.swing.JButton();
        cancelarButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        qtEstoqueFormattedTextField = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setText("Descrição");

        descricaoTextFiel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descricaoTextFielActionPerformed(evt);
            }
        });

        salvarButton.setText("Salvar");
        salvarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarButtonActionPerformed(evt);
            }
        });

        cancelarButton.setText("Cancelar");
        cancelarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarButtonActionPerformed(evt);
            }
        });

        jLabel4.setText("Qt. Estoque");

        qtEstoqueFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));

        jLabel2.setText("Insumos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(168, 168, 168))
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(salvarButton)
                        .addGap(51, 51, 51)
                        .addComponent(cancelarButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(qtEstoqueFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(descricaoTextFiel, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(descricaoTextFiel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(qtEstoqueFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cancelarButton)
                            .addComponent(salvarButton))
                        .addGap(72, 72, 72))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void descricaoTextFielActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descricaoTextFielActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descricaoTextFielActionPerformed

    private void cancelarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarButtonActionPerformed
        jif.dispose();
    }//GEN-LAST:event_cancelarButtonActionPerformed

    private void salvarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarButtonActionPerformed
           if( !descricaoTextFiel.getText().equals("")
                
                   && Double.parseDouble(qtEstoqueFormattedTextField.getText())> 0){
            
                
                insumo.setDescricao(descricaoTextFiel.getText());
                    insumo.setQuantidadeEstoque(Double.parseDouble(qtEstoqueFormattedTextField.getText()));
                
                InsumoBO bo = new InsumoBO();
                if (insumo.getId()==0)
                bo.save(insumo);
                else{
                    bo.update(insumo);
                }
                 JOptionPane.showMessageDialog(null,"Insumo Salvo com sucesso");
            }
         
    }//GEN-LAST:event_salvarButtonActionPerformed

    private Insumo insumo;
    private final JInternalFrame jif;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelarButton;
    private javax.swing.JTextField descricaoTextFiel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JFormattedTextField qtEstoqueFormattedTextField;
    private javax.swing.JButton salvarButton;
    // End of variables declaration//GEN-END:variables
}
