/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.com.cafi.barzinhodesktop.visao;

import bo.ProdutoBO;
import br.com.cafi.barzinhodesktop.modelo.entidade.Produto;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jk-Sa
 */
public class ListarProduto extends javax.swing.JPanel {

    
    /**
     * Creates new form ListarProduto
     */
    public ListarProduto() {
        initComponents();
        carregarTabela();
    }

    private List<Produto> lista;

    private void carregarTabela(){
        limparTabela();
         ProdutoBO bo = new ProdutoBO();
        lista = bo.findAll();
        DefaultTableModel model
                = (DefaultTableModel) jTable1.getModel();
        for (Produto obj : lista) {
            model.addRow(new Object[]{obj.getId(), obj.getDescricao(),
                obj.getPrecoVenda(), obj.getPrecoCompra(), obj.getQuantidadeEstoque()});
        }
    }
    
    private void limparTabela(){
         DefaultTableModel model
                = (DefaultTableModel) jTable1.getModel();
         for (int i =0; i<model.getRowCount();i++){
             model.removeRow(0);
         }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        deletarButton = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Descrição", "Preço Venda", "Preço Compra", "Qt. Estoque"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        deletarButton.setText("Deletar");
        deletarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(deletarButton)
                .addGap(67, 67, 67))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(deletarButton)
                .addContainerGap(62, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void deletarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletarButtonActionPerformed
        
        
        DefaultTableModel model
                = (DefaultTableModel) jTable1.getModel();
        long id = (long)model.getValueAt(jTable1.getSelectedRow(), 0);
        ProdutoBO bo = new ProdutoBO();
        Produto p = bo.getById(id);
        System.out.println("Tentando apagar o usuário "+p.getDescricao());
        bo.delete(p);
        JOptionPane.showConfirmDialog(null, "Removido com sucesso!");
        carregarTabela();
    }//GEN-LAST:event_deletarButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deletarButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
