/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.com.cafi.barzinhodesktop.visao;

import bo.PedidoBO;
import br.com.cafi.barzinhodesktop.modelo.entidade.Pedido;
import java.util.List;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jk-Sa
 */
public class ListarPedido extends javax.swing.JPanel {

    private TelaInicial telaInicial;
    JInternalFrame jif;

    public ListarPedido(TelaInicial telainicial, JInternalFrame jif) {
        initComponents();
        carregarTabela();
        this.telaInicial = telainicial;
        this.jif = jif;
    }

    private List<Pedido> lista;

    private void carregarTabela() {
        limparTabela();
        PedidoBO bo = new PedidoBO();
        lista = bo.findAll();
        DefaultTableModel model
                = (DefaultTableModel) jTable1.getModel();
        for (Pedido obj : lista) {
            model.addRow(new Object[]{obj.getId(), obj.getObservacao(),
                obj.getStatus(), obj.getComanda() == null ? "Delivery" : obj.getComanda().getNome(), obj.getCliente() == null ? "sem cliente" : obj.getCliente().getNome(), obj.getTipo()});
        }
    }

    private void limparTabela() {
        DefaultTableModel model
                = (DefaultTableModel) jTable1.getModel();
        for (int i = 0; i < model.getRowCount(); i++) {
            model.removeRow(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        deletarButton = new javax.swing.JButton();
        editarButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Total", "Status", "Mesa", "Cliente", "Tipo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        deletarButton.setText("Deletar");
        deletarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletarButtonActionPerformed(evt);
            }
        });

        editarButton.setText("Editar");
        editarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarButtonActionPerformed(evt);
            }
        });

        jButton1.setText("Entrega Realizada");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 642, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(editarButton)
                        .addGap(18, 18, 18)
                        .addComponent(deletarButton)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editarButton)
                    .addComponent(deletarButton)
                    .addComponent(jButton1))
                .addContainerGap(29, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void deletarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletarButtonActionPerformed
        int opcao = JOptionPane.showConfirmDialog(null, "Deseja remover?");
        if (opcao == JOptionPane.YES_OPTION) {
            DefaultTableModel model
                    = (DefaultTableModel) jTable1.getModel();
            long id = (long) model.getValueAt(jTable1.getSelectedRow(), 0);
            PedidoBO bo = new PedidoBO();
            Pedido u = bo.getById(id);
            System.out.println("Tentando apagar o pedido " + u.getComanda().getNome());
            bo.delete(u);
            limparTabela();
            carregarTabela();
        }
    }//GEN-LAST:event_deletarButtonActionPerformed

    private void editarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarButtonActionPerformed
        DefaultTableModel model
                = (DefaultTableModel) jTable1.getModel();
        long id = (Long) model.getValueAt(jTable1.getSelectedRow(), 0);
        PedidoBO bo = new PedidoBO();
        Pedido p = bo.getById(id);
        //abrir novo internalframe, devido isso, precisamos do desktoppanel da
        //tela inicial
        JInternalFrame jif = new JInternalFrame("Editar pedido");
        jif.setBounds(0, 0, 805, 439);
        jif.setVisible(true);
        jif.setClosable(true);
        jif.setResizable(true);
        // CadastrarPedido cp = new CadastrarPedido(jif,p);
        // jif.add(cp);
        this.telaInicial.getDesktopPane().add(jif);
        this.jif.dispose();
    }//GEN-LAST:event_editarButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DefaultTableModel model
                = (DefaultTableModel) jTable1.getModel();
        long id = (Long) model.getValueAt(jTable1.getSelectedRow(), 0);
        PedidoBO bo = new PedidoBO();
        Pedido p = bo.getById(id);
        if (p.getCliente() != null) {
            p.setStatus("Entrega finalizada");
            PedidoBO pbo = new PedidoBO();
            pbo.update(p);
            carregarTabela();
        }

    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deletarButton;
    private javax.swing.JButton editarButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
