/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.com.cafi.barzinhodesktop.visao;

import bo.MesaBO;
import bo.PedidoBO;
import br.com.cafi.barzinhodesktop.modelo.entidade.Comanda;
import br.com.cafi.barzinhodesktop.modelo.entidade.Pedido;
import java.util.Date;
import java.util.List;
import javax.swing.JInternalFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jk-Sa
 */
public class MesaComanda extends javax.swing.JPanel {

    /**
     * Creates new form MesaComanda
     */
    public MesaComanda(JInternalFrame jif, TelaInicial tl) {
        initComponents();
        carregarTabela();
        this.jif = jif;
        this.tl = tl;
    }

    private List<Comanda> lista;

    private void carregarTabela() {
        limparTabela();
        MesaBO bo = new MesaBO();
        lista = bo.findAll();
        DefaultTableModel model
                = (DefaultTableModel) jTable1.getModel();
        for (Comanda obj : lista) {
            model.addRow(new Object[]{obj.getId(), obj.getNome(),
                obj.isStatus() ? "Ocupado" : "livre"});
        }
    }

    private void limparTabela() {
        DefaultTableModel model
                = (DefaultTableModel) jTable1.getModel();
        for (int i = 0; i < model.getRowCount(); i++) {
            model.removeRow(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        pedidoButton = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nome", "Status"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        pedidoButton.setText("Realizar Pedido");
        pedidoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pedidoButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(pedidoButton)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pedidoButton)
                .addContainerGap(151, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void pedidoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pedidoButtonActionPerformed
        DefaultTableModel dm = (DefaultTableModel) jTable1.getModel();
        Long idComanda = Long.parseLong(dm.getValueAt(jTable1.getSelectedRow(), 0) + "");
        MesaBO bo = new MesaBO();
        Comanda comanda = bo.getById(idComanda);

        if (comanda.isStatus() == false) {
            comanda.setStatus(true);
            MesaBO Mbo = new MesaBO();
            Mbo.update(comanda);
            Pedido p = new Pedido();
            p.setDataDoPedido(new Date(System.currentTimeMillis()));
            p.setComanda(comanda);
            PedidoBO Pbo = new PedidoBO();

            Pbo.save(p);

            JInternalFrame jif = new JInternalFrame("Cadastrar Comandas");
            jif.setVisible(true);
            jif.setBounds(0, 0, 805, 540);
            jif.setClosable(true);
            jif.setResizable(true);
            CadastrarPedido cc = new CadastrarPedido(jif, comanda, p);
            jif.add(cc);
            tl.getDesktopPane().add(jif);
            this.jif.dispose();
        } else {
            PedidoBO boP = new PedidoBO();
            
            List<Pedido> l = boP.findWhere(comanda.getId());

            Long idPedido = l.get(0).getId();

            Pedido p = boP.getById(idPedido);

            JInternalFrame jif = new JInternalFrame("Cadastrar Comandas");
            jif.setVisible(true);
            jif.setBounds(0, 0, 805, 540);
            jif.setClosable(true);
            jif.setResizable(true);
            CadastrarPedido cc = new CadastrarPedido(jif, comanda, p);
            jif.add(cc);
            tl.getDesktopPane().add(jif);
            this.jif.dispose();
        }


    }//GEN-LAST:event_pedidoButtonActionPerformed

    private TelaInicial tl;
    private JInternalFrame jif;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton pedidoButton;
    // End of variables declaration//GEN-END:variables
}
