/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.com.cafi.barzinhodesktop.visao;

import bo.ProdutoBO;
import br.com.cafi.barzinhodesktop.modelo.entidade.Produto;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Aluno
 */
public class ReposicaoProduto extends javax.swing.JPanel {

    /**
     * Creates new form Reposicao
     */
    public ReposicaoProduto(TelaInicial ti, JInternalFrame jif) {
        initComponents();
        carregarTabela();
        this.telaInicial = ti;
        this.jif = jif;
    }

    JInternalFrame jif;
    TelaInicial telaInicial;
    private List<Produto> lista;

    private void carregarTabela() {
        limparTabela();
        ProdutoBO bo = new ProdutoBO();
        lista = bo.findAll();
        DefaultTableModel model
                = (DefaultTableModel) produtoTable.getModel();
        for (Produto obj : lista) {
            model.addRow(new Object[]{obj.getId(), obj.getDescricao(),
                obj.getQuantidadeEstoque()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        produtoTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        codigoTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        quantidadeTextField = new javax.swing.JTextField();
        produtoLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jLabel1.setText("Reposição Produto");

        produtoTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Produto", "Quantidade"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        produtoTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                produtoTableMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(produtoTable);

        jLabel2.setText("Código");

        codigoTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                codigoTextFieldKeyReleased(evt);
            }
        });

        jLabel3.setText("Quantidade");

        quantidadeTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                quantidadeTextFieldKeyReleased(evt);
            }
        });

        produtoLabel.setText("Produto: ");

        jButton1.setText("Repor Estoque");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 419, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(codigoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(quantidadeTextField))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(produtoLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(164, 164, 164))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(codigoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(quantidadeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(produtoLabel)
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(84, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void codigoTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codigoTextFieldKeyReleased
        atualizarDadosDoProdutoSelecionado();
        if (KeyEvent.VK_ENTER == evt.getKeyCode()) {
            repor();
        }
    }//GEN-LAST:event_codigoTextFieldKeyReleased

    private void quantidadeTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_quantidadeTextFieldKeyReleased
        if (KeyEvent.VK_ENTER == evt.getKeyCode())
            repor();
    }//GEN-LAST:event_quantidadeTextFieldKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        repor();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void produtoTableMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_produtoTableMouseReleased
        DefaultTableModel modelo = (DefaultTableModel) produtoTable.getModel();
        Long id = (Long) modelo.getValueAt(produtoTable.getSelectedRow(), 0);
        codigoTextField.setText(id+"");
        atualizarDadosDoProdutoSelecionado();
    }//GEN-LAST:event_produtoTableMouseReleased

    private void atualizarDadosDoProdutoSelecionado(){
        ProdutoBO bo = new ProdutoBO();
        produtoSelecionado = bo.getById(Long.parseLong(codigoTextField.getText()));
        produtoLabel.setText("Produto: " + produtoSelecionado.getDescricao());
    }
    
    Produto produtoSelecionado;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField codigoTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel produtoLabel;
    private javax.swing.JTable produtoTable;
    private javax.swing.JTextField quantidadeTextField;
    // End of variables declaration//GEN-END:variables

    private void repor() {

        produtoSelecionado.setQuantidadeEstoque(
                produtoSelecionado.getQuantidadeEstoque()
                + Double.parseDouble(quantidadeTextField.getText()));
        if (JOptionPane.showConfirmDialog(null,
                "Deseja adcionar ao estoque de " + produtoSelecionado.getDescricao()
                + " uma quantidade de " + quantidadeTextField.getText()) == JOptionPane.YES_OPTION) {
            ProdutoBO bo = new ProdutoBO();
            bo.update(produtoSelecionado);

        }
    }

    private void limparTabela() {
        DefaultTableModel modelo = (DefaultTableModel) produtoTable.getModel();
        while (modelo.getRowCount() > 0) {
            modelo.removeRow(0);
        }
    }
}
